### ISSUE TITLE
TypeConversions doesn't honor unsigned smallint and need better error handling

### ISSUE THREAD

**Issue by dserdyuk** [memsql/memsql-spark-connector#41]
One of our column in MemSQL database is defined as 
` start_video_pos smallint(5) unsigned DEFAULT NULL`
TypeConversions treats  unsigned smallint as spark's ShortType which causes an exception while reading data event though value is in the unsigned smallint range. We suspect it needs to take into account  sign bit and use IntergerType to fit value

We use `memsql-connector_2.11:2.0.5` and are getting reading error with following  trace: 

> WARN TaskSetManager: Lost task 11.0 in stage 0.0 (TID 11, ......compute.internal, executor 1): org.apache.spark.SparkException: Task failed while writing rows.
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:285)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:197)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:196)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLDataException: Value '65535' is outside of valid range for type java.lang.Short
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:530)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:505)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:479)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:489)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:85)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getShort(ResultSetImpl.java:863)
	at org.apache.commons.dbcp2.DelegatingResultSet.getShort(DelegatingResultSet.java:211)
	at org.apache.commons.dbcp2.DelegatingResultSet.getShort(DelegatingResultSet.java:211)
	at com.memsql.spark.connector.dataframe.TypeConversions$.GetJDBCValue(TypeConversions.scala:80)
	at com.memsql.spark.connector.util.JDBCImplicits$ResultSetHelpers$$anonfun$toRow$1.apply(JDBCImplicits.scala:26)
	at com.memsql.spark.connector.util.JDBCImplicits$ResultSetHelpers$$anonfun$toRow$1.apply(JDBCImplicits.scala:23)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.memsql.spark.connector.util.JDBCImplicits$ResultSetHelpers.toRow(JDBCImplicits.scala:23)
	at com.memsql.spark.connector.MemSQLQueryRelation$$anonfun$1.apply(MemSQLRelation.scala:45)
	at com.memsql.spark.connector.MemSQLQueryRelation$$anonfun$1.apply(MemSQLRelation.scala:45)
	at com.memsql.spark.connector.rdd.MemSQLRDD$$anon$1.getNext(MemSQLRDD.scala:275)
	at com.memsql.spark.connector.util.NextIterator.hasNext(NextIterator.scala:74)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:614)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.execute(FileFormatWriter.scala:380)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:269)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:267)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1411)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:272)
	... 8 more
Caused by: com.mysql.cj.core.exceptions.NumberOutOfRange: Value '65535' is outside of valid range for type java.lang.Short
	at com.mysql.cj.core.io.IntegerBoundsEnforcer.createFromLong(IntegerBoundsEnforcer.java:50)
	at com.mysql.cj.core.io.BaseDecoratingValueFactory.createFromLong(BaseDecoratingValueFactory.java:58)
	at com.mysql.cj.core.io.MysqlTextValueDecoder.decodeUInt2(MysqlTextValueDecoder.java:189)
	at com.mysql.cj.mysqla.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:84)
	at com.mysql.cj.mysqla.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:225)
	at com.mysql.cj.mysqla.result.ByteArrayRow.getValue(ByteArrayRow.java:84)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getNonStringValueFromRow(ResultSetImpl.java:630)
	... 34 more

It would be useful to add more logging in JDBCImplicits.toRow() to log which column causes the error instead of just propagating Mysql error

**Comment by carlsverre** [comment]
Fixed in the next version of the connector: https://github.com/memsql/memsql-spark-connector/tree/3.0.0-beta
